export enum Param {
  SOURCE_BRANCH_NAME = 'SOURCE_BRANCH_NAME',
  SOURCE_CONNECTION_ARN = 'SOURCE_CONNECTION_ARN',
  DEPLOY_ENV = 'DEPLOY_ENV',
  ENV_STAGE_PREFIX = 'ENV_STAGE_PREFIX',
  SOURCE_REPO_NAME = 'SOURCE_REPO_NAME',
  SLACK_CHATBOT_ARN = 'SLACK_CHATBOT_ARN',
  SLACK_NOTIFICATION = 'SLACK_NOTIFICATION',
  CLOUDFRONT_WAF_ARN = 'CLOUDFRONT_WAF_ARN',
  ENABLE_WAF = 'ENABLE_WAF',
  APPLICATION_NAME = 'APPLICATION_NAME',
  SECONDARY_BUCKET_NAME = 'SECONDARY_BUCKET_NAME',
}
